<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Распродажа");

?><?$APPLICATION->IncludeComponent(
	"custom:catalog.smart.filter",
	"skidka_filter",
	Array(
		"CACHE_GROUPS" => "N",
		"CACHE_TIME" => "36000000",
		"CACHE_TYPE" => "A",
		"COMPONENT_TEMPLATE" => "discount_filter",
		"CONVERT_CURRENCY" => "N",
		"DISPLAY_ELEMENT_COUNT" => "Y",
		"FILTER_NAME" => "arrFilter",
		"FILTER_VIEW_MODE" => "vertical",
		"HIDE_NOT_AVAILABLE" => "Y",
		"HIDE_WITHOUT_DISCOUNT" => "Y",
		"IBLOCK_ID" => "41",
		"IBLOCK_TYPE" => "catalog",
		"PAGER_PARAMS_NAME" => "arrPager",
		"POPUP_POSITION" => "left",
		"PRICE_CODE" => array(),
		"SAVE_IN_SESSION" => "N",
		"SECTION_CODE" => "",
		"SECTION_CODE_PATH" => "",
		"SECTION_DESCRIPTION" => "-",
		"SECTION_ID" => "",
		"SECTION_TITLE" => "-",
		"SEF_MODE" => "N",
		"SEF_RULE" => "",
		"SHOW_ALL_WO_SECTION" => "Y",
		"SMART_FILTER_PATH" => "",
		"TEMPLATE_THEME" => "site",
		"XML_EXPORT" => "N"
	)
);?>
<div id="catalog-filter">

<?$APPLICATION->IncludeComponent(
            "bxready.market2:catalog.section",
            ".default",
            array(
                "ACTION_VARIABLE" => "action",
                "ADD_PICT_PROP" => "-",
                "ADD_PROPERTIES_TO_BASKET" => "Y",
                "ADD_SECTIONS_CHAIN" => "N",
                "ADD_TO_BASKET_ACTION" => "ADD",
                "AJAX_MODE" => "N",
                "AJAX_OPTION_ADDITIONAL" => "",
                "AJAX_OPTION_HISTORY" => "N",
                "AJAX_OPTION_JUMP" => "N",
                "AJAX_OPTION_STYLE" => "Y",
                "BACKGROUND_IMAGE" => "-",
                "BASKET_URL" => "/personal/basket.php",
                "BROWSER_TITLE" => "-",
                "BXREADY_ELEMENT_ADDCLASS_BIG" => "",
                "BXREADY_ELEMENT_ADDCLASS_SMALL" => "",
                "BXREADY_ELEMENT_ADDCLASS_STANDART" => "",
                "BXREADY_ELEMENT_DRAW_BIG" => "ecommerce.m2.big.v1",
                "BXREADY_ELEMENT_DRAW_SMALL" => "ecommerce.m2.small.v1",
                "BXREADY_ELEMENT_DRAW_STANDART" => "ecommerce.m2.v1",
                "BXREADY_ELEMENT_EXT_PARAMS_BIG" => "arrExtParams",
                "BXREADY_ELEMENT_EXT_PARAMS_SMALL" => "arrExtParams",
                "BXREADY_ELEMENT_EXT_PARAMS_STANDART" => "arrExtParams",
                "BXREADY_LIST_MARKER_TYPE_BIG" => "circle.horizontal",
                "BXREADY_LIST_MARKER_TYPE_STANDART" => "circle.horizontal",
                "BXREADY_LIST_OWN_MARKER_USE_STANDART" => "N",
                "BXREADY_USER_TYPES_BIG" => "N",
                "BXREADY_USER_TYPES_SMALL" => "N",
                "BXREADY_USER_TYPES_STANDART" => "N",
                "BXREADY_USE_ELEMENTCLASS_BIG" => "Y",
                "BXREADY_USE_ELEMENTCLASS_SMALL" => "Y",
                "BXREADY_USE_ELEMENTCLASS_STANDART" => "Y",
                "BXREADY_VERTICAL_ALIGN_BIG" => "Y",
                "BXREADY_VERTICAL_ALIGN_SMALL" => "Y",
                "BXREADY_VERTICAL_ALIGN_STANDART" => "Y",
                "BXR_IMG_MAX_HEIGHT_BIG" => "210",
                "BXR_IMG_MAX_HEIGHT_SMALL" => "90",
                "BXR_IMG_MAX_HEIGHT_STANDART" => "180",
                "BXR_IMG_MAX_WIDTH_BIG" => "210",
                "BXR_IMG_MAX_WIDTH_SMALL" => "90",
                "BXR_IMG_MAX_WIDTH_STANDART" => "180",
                "BXR_SHOW_ACTION_TIMER_BIG" => "N",
                "BXR_SHOW_ACTION_TIMER_STANDART" => "N",
                "BXR_SHOW_ARTICLE_BIG" => "Y",
                "BXR_SHOW_ARTICLE_STANDART" => "Y",
                "BXR_SHOW_PREVIEW_TEXT_BIG" => "Y",
                "BXR_SHOW_RATING_STANDART" => "N",
                "BXR_SHOW_SLIDER_BIG" => "Y",
                "BXR_SHOW_SLIDER_STANDART" => "Y",
                "BXR_SKU_PROPS_SHOW_TYPE_BIG" => "rounded",
                "BXR_SKU_PROPS_SHOW_TYPE_STANDART" => "square",
                "BXR_SLIDER_INTERVAL_BIG" => "3000",
                "BXR_SLIDER_INTERVAL_STANDART" => "0",
                "BXR_TILE_SHOW_PROPERTIES_STANDART" => "N",
                "BXR_USE_FAST_VIEW_BIG" => "N",
                "BXR_USE_FAST_VIEW_SMALL" => "Y",
                "BXR_USE_FAST_VIEW_STANDART" => "N",
                "CACHE_FILTER" => "N",
                "CACHE_GROUPS" => "Y",
                "CACHE_TIME" => "36000000",
                "CACHE_TYPE" => "A",
                "COMPATIBLE_MODE" => "Y",
                "COMPONENT_TEMPLATE" => ".default",
                "CONVERT_CURRENCY" => "Y",
                "CUSTOM_FILTER" => "",
                "DETAIL_URL" => "",
                "DISABLE_INIT_JS_IN_COMPONENT" => "N",
                "DISPLAY_BOTTOM_PAGER" => "Y",
                "DISPLAY_COMPARE" => "N",
                "DISPLAY_TOP_PAGER" => "N",
                "ELEMENT_SORT_FIELD" => $arSortGlobal["sort"],
                "ELEMENT_SORT_FIELD2" => "id",
                "ELEMENT_SORT_ORDER" => $arSortGlobal["sort_order"],
                "ELEMENT_SORT_ORDER2" => "desc",
                "FILTER_NAME" => "arrFilter",
                "HIDE_NOT_AVAILABLE" => "Y",
                "HIDE_NOT_AVAILABLE_OFFERS" => "Y",
                "IBLOCK_ID" => "41",
                "IBLOCK_TYPE" => "catalog",
                "INCLUDE_SUBSECTIONS" => "Y",
                "LAZY_LOAD" => "Y",
                "LINE_ELEMENT_COUNT" => "3",
                "LOAD_ON_SCROLL" => "N",
                "MESSAGE_404" => "",
                "MESS_BTN_ADD_TO_BASKET" => "В корзину",
                "MESS_BTN_BUY" => "Купить",
                "MESS_BTN_DETAIL" => "Подробнее",
                "MESS_BTN_FAST_VIEW_SMALL" => "Быстрый просмотр",
                "MESS_BTN_LAZY_LOAD" => "Показать ещё",
                "MESS_BTN_SUBSCRIBE" => "Подписаться",
                "MESS_NOT_AVAILABLE" => "Нет в наличии",
                "META_DESCRIPTION" => "-",
                "META_KEYWORDS" => "-",
                "OFFERS_LIMIT" => "5",
                "PAGER_BASE_LINK_ENABLE" => "N",
                "PAGER_DESC_NUMBERING" => "N",
                "PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
                "PAGER_SHOW_ALL" => "N",
                "PAGER_SHOW_ALWAYS" => "N",
                "PAGER_TEMPLATE" => ".default",
                "PAGER_TITLE" => "Товары",
                "PAGE_ELEMENT_COUNT" => "18",
                "PARTIAL_PRODUCT_PROPERTIES" => "Y",
                "PRICE_CODE" => array(
                    0 => "Розница",
                ),
                "PRICE_VAT_INCLUDE" => "Y",
                "PRODUCT_ID_VARIABLE" => "id",
                "PRODUCT_PROPERTIES" => array(
                ),
                "PRODUCT_PROPS_VARIABLE" => "prop",
                "PRODUCT_QUANTITY_VARIABLE" => "quantity",
                "PRODUCT_ROW_VARIANTS" => "[{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false}]",
                "PRODUCT_SUBSCRIPTION" => "Y",
                "PROPERTY_CODE" => array(
                    0 => "",
                    1 => "",
                ),
                "PROPERTY_CODE_MOBILE" => array(
                ),
                "RCM_PROD_ID" => $_REQUEST["PRODUCT_ID"],
                "RCM_TYPE" => "personal",
                "SECTION_CODE" => "",
                "SECTION_ID" => "",
                "SECTION_ID_VARIABLE" => "SECTION_ID",
                "SECTION_URL" => "",
                "SECTION_USER_FIELDS" => array(
                    0 => "",
                    1 => "",
                ),
                "SEF_MODE" => "N",
                "SET_BROWSER_TITLE" => "Y",
                "SET_LAST_MODIFIED" => "N",
                "SET_META_DESCRIPTION" => "Y",
                "SET_META_KEYWORDS" => "Y",
                "SET_STATUS_404" => "N",
                "SET_TITLE" => "Y",
                "SHOW_404" => "N",
                "SHOW_ALL_WO_SECTION" => "Y",
                "SHOW_CLOSE_POPUP" => "Y",
                "SHOW_FROM_SECTION" => "N",
                "SHOW_MAX_QUANTITY" => "N",
                "SHOW_OLD_PRICE" => "Y",
                "SHOW_PRICE_COUNT" => "1",
                "TEMPLATE_THEME" => "site",
                "USE_ENHANCED_ECOMMERCE" => "N",
                "USE_MAIN_ELEMENT_SECTION" => "N",
                "USE_PRICE_COUNT" => "N",
                "USE_PRODUCT_QUANTITY" => "N",
                "OFFERS_SORT_FIELD" => "sort",
                "OFFERS_SORT_ORDER" => "asc",
                "OFFERS_SORT_FIELD2" => "id",
                "OFFERS_SORT_ORDER2" => "desc",
                "OFFERS_FIELD_CODE" => array(
                    0 => "",
                    1 => "",
                ),
                "OFFERS_PROPERTY_CODE" => array(
                    0 => "",
                    1 => "",
                ),
                "PRODUCT_DISPLAY_MODE" => "N",
                "OFFERS_CART_PROPERTIES" => array(
                ),
                "CURRENCY_ID" => "UAH"
            ),
            false
        );?>
    </div>
<br>
<style>
    .bxr-b20.bxr-cloud-all.bxr-cloud-padding {
        padding: 1rem 2rem;
    }
.bxr-template-container h1.bxr-h1 {
margin: 0;
border-bottom: 0px solid #fff;
}
	.navig {
		display: none!important
	}
</style><?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>