<div class="jcarousel-row">
    <div class="menu">
        <a value="skidki" class="bxr-bestsellers-first bxr-bestsellers-group bxr-color-hover best-active"><div>Товары со скидкой</div></a>
<!--        <a value="contactless" class="bxr-bestsellers-group bxr-color-hover"><div>Бесконтактная доставка</div></a>-->
        <a value="new" class="bxr-bestsellers-group bxr-color-hover"><div>Новые поступления</div></a>
        <a value="lider" class="bxr-bestsellers-group bxr-color-hover"><div>Лидеры продаж</div></a>
        <div class="clearfix"></div>
        <div class="best-blocks best-block-skidki">
            <?
            $APPLICATION->IncludeComponent(
                "bxready.market2:catalog.section",
                "skidki",
                array(
                    "ACTION_VARIABLE" => "action",
                    "ADD_PICT_PROP" => "-",
                    "ADD_PROPERTIES_TO_BASKET" => "Y",
                    "ADD_SECTIONS_CHAIN" => "Y",
                    "ADD_TO_BASKET_ACTION" => "ADD",
                    "AJAX_MODE" => "Y",
                    "AJAX_OPTION_ADDITIONAL" => "",
                    "AJAX_OPTION_HISTORY" => "N",
                    "AJAX_OPTION_JUMP" => "N",
                    "AJAX_OPTION_STYLE" => "Y",
                    "BACKGROUND_IMAGE" => "-",
                    "BASKET_URL" => "/personal/basket.php",
                    "BROWSER_TITLE" => "-",
                    "BXREADY_ELEMENT_ADDCLASS_BIG" => "",
                    "BXREADY_ELEMENT_ADDCLASS_SMALL" => "",
                    "BXREADY_ELEMENT_ADDCLASS_STANDART" => "",
                    "BXREADY_ELEMENT_DRAW_BIG" => "ecommerce.m2.big.v1",
                    "BXREADY_ELEMENT_DRAW_LISTPAGE" => "ecommerce.m2.v1",
                    "BXREADY_ELEMENT_DRAW_SMALL" => "ecommerce.m2.small.v1",
                    "BXREADY_ELEMENT_DRAW_STANDART" => "ecommerce.m2.v1",
                    "BXREADY_ELEMENT_EXT_PARAMS_BIG" => "arrExtParams",
                    "BXREADY_ELEMENT_EXT_PARAMS_SMALL" => "arrExtParams",
                    "BXREADY_ELEMENT_EXT_PARAMS_STANDART" => "arrExtParams",
                    "BXREADY_LIST_MARKER_TYPE_BIG" => "circle.horizontal",
                    "BXREADY_LIST_MARKER_TYPE_STANDART" => "circle.horizontal",
                    "BXREADY_LIST_OWN_MARKER_USE_STANDART" => "N",
                    "BXREADY_USER_TYPES_BIG" => "N",
                    "BXREADY_USER_TYPES_SMALL" => "N",
                    "BXREADY_USER_TYPES_STANDART" => "N",
                    "BXREADY_USE_ELEMENTCLASS_BIG" => "Y",
                    "BXREADY_USE_ELEMENTCLASS_SMALL" => "Y",
                    "BXREADY_USE_ELEMENTCLASS_STANDART" => "Y",
                    "BXREADY_VERTICAL_ALIGN_BIG" => "Y",
                    "BXREADY_VERTICAL_ALIGN_SMALL" => "Y",
                    "BXREADY_VERTICAL_ALIGN_STANDART" => "Y",
                    "BXR_IMG_MAX_HEIGHT_BIG" => "210",
                    "BXR_IMG_MAX_HEIGHT_SMALL" => "90",
                    "BXR_IMG_MAX_HEIGHT_STANDART" => "250",
                    "BXR_IMG_MAX_WIDTH_BIG" => "210",
                    "BXR_IMG_MAX_WIDTH_SMALL" => "90",
                    "BXR_IMG_MAX_WIDTH_STANDART" => "250",
                    "BXR_SHOW_ACTION_TIMER_BIG" => "N",
                    "BXR_SHOW_ACTION_TIMER_STANDART" => "N",
                    "BXR_SHOW_ARTICLE_BIG" => "Y",
                    "BXR_SHOW_ARTICLE_STANDART" => "Y",
                    "BXR_SHOW_PREVIEW_TEXT_BIG" => "Y",
                    "BXR_SHOW_RATING_STANDART" => "N",
                    "BXR_SHOW_SLIDER_BIG" => "Y",
                    "BXR_SHOW_SLIDER_STANDART" => "Y",
                    "BXR_SKU_PROPS_SHOW_TYPE_BIG" => "rounded",
                    "BXR_SKU_PROPS_SHOW_TYPE_STANDART" => "square",
                    "BXR_SLIDER_INTERVAL_BIG" => "3000",
                    "BXR_SLIDER_INTERVAL_STANDART" => "0",
                    "BXR_TILE_SHOW_PROPERTIES_STANDART" => "N",
                    "BXR_USE_FAST_VIEW_BIG" => "N",
                    "BXR_USE_FAST_VIEW_SMALL" => "Y",
                    "BXR_USE_FAST_VIEW_STANDART" => "N",
                    "CACHE_FILTER" => "N",
                    "CACHE_GROUPS" => "Y",
                    "CACHE_TIME" => "36000000",
                    "CACHE_TYPE" => "A",
                    "COMPATIBLE_MODE" => "Y",
                    "COMPONENT_TEMPLATE" => "skidki",
                    "CONVERT_CURRENCY" => "N",
                    "CUSTOM_FILTER" => "{\"CLASS_ID\":\"CondGroup\",\"DATA\":{\"All\":\"OR\",\"True\":\"True\"},\"CHILDREN\":[{\"CLASS_ID\":\"CondIBProp:44:372\",\"DATA\":{\"logic\":\"Equal\",\"value\":\"35\"}},{\"CLASS_ID\":\"CondIBProp:44:372\",\"DATA\":{\"logic\":\"Equal\",\"value\":\"30\"}},{\"CLASS_ID\":\"CondIBProp:44:372\",\"DATA\":{\"logic\":\"Equal\",\"value\":\"25\"}},{\"CLASS_ID\":\"CondIBProp:44:372\",\"DATA\":{\"logic\":\"Equal\",\"value\":\"20\"}},{\"CLASS_ID\":\"CondIBProp:44:372\",\"DATA\":{\"logic\":\"Equal\",\"value\":\"15\"}},{\"CLASS_ID\":\"CondIBProp:44:372\",\"DATA\":{\"logic\":\"Equal\",\"value\":\"10\"}},{\"CLASS_ID\":\"CondIBProp:44:372\",\"DATA\":{\"logic\":\"Equal\",\"value\":\"5\"}},{\"CLASS_ID\":\"CondIBProp:44:372\",\"DATA\":{\"logic\":\"Equal\",\"value\":\"40\"}},{\"CLASS_ID\":\"CondIBProp:44:372\",\"DATA\":{\"logic\":\"Equal\",\"value\":\"45\"}},{\"CLASS_ID\":\"CondIBProp:44:372\",\"DATA\":{\"logic\":\"Equal\",\"value\":\"50\"}},{\"CLASS_ID\":\"CondIBProp:44:372\",\"DATA\":{\"logic\":\"Equal\",\"value\":\"55\"}},{\"CLASS_ID\":\"CondIBProp:44:372\",\"DATA\":{\"logic\":\"Equal\",\"value\":\"60\"}}]}",
                    "DETAIL_URL" => "",
                    "DISABLE_INIT_JS_IN_COMPONENT" => "N",
                    "DISPLAY_BOTTOM_PAGER" => "Y",
                    "DISPLAY_COMPARE" => "N",
                    "DISPLAY_TOP_PAGER" => "N",
                    "ELEMENT_SORT_FIELD" => $arSortGlobal["sort"],
                    "ELEMENT_SORT_FIELD2" => "rand",
                    "ELEMENT_SORT_ORDER" => $arSortGlobal["sort_order"],
                    "ELEMENT_SORT_ORDER2" => "desc",
                    "FILTER_NAME" => "arrFilter",
                    "HIDE_NOT_AVAILABLE" => "Y",
                    "HIDE_NOT_AVAILABLE_OFFERS" => "Y",
                    "IBLOCK_ID" => "44",
                    "IBLOCK_TYPE" => "catalog",
                    "INCLUDE_SUBSECTIONS" => "Y",
                    "LAZY_LOAD" => "N",
                    "LINE_ELEMENT_COUNT" => "4",
                    "LOAD_ON_SCROLL" => "N",
                    "MESSAGE_404" => "",
                    "MESS_BTN_ADD_TO_BASKET" => "В корзину",
                    "MESS_BTN_BUY" => "Купить",
                    "MESS_BTN_DETAIL" => "Подробнее",
                    "MESS_BTN_FAST_VIEW_SMALL" => "Быстрый просмотр",
                    "MESS_BTN_LAZY_LOAD" => "Показать ещё",
                    "MESS_BTN_SUBSCRIBE" => "Подписаться",
                    "MESS_NOT_AVAILABLE" => "Нет в наличии",
                    "META_DESCRIPTION" => "-",
                    "META_KEYWORDS" => "-",
                    "OFFERS_LIMIT" => "5",
                    "PAGER_BASE_LINK_ENABLE" => "N",
                    "PAGE_BLOCK_TITLE" => "",
                    "PAGER_DESC_NUMBERING" => "N",
                    "PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
                    "PAGER_SHOW_ALL" => "N",
                    "PAGER_SHOW_ALWAYS" => "N",
                    "PAGER_TEMPLATE" => "custom_new",
                    "PAGER_TITLE" => "Товары",
                    "PAGE_ELEMENT_COUNT" => "8",
                    "PARTIAL_PRODUCT_PROPERTIES" => "Y",
                    "PRICE_CODE" => array(
                        0 => "Розница",
                    ),
                    "PRICE_VAT_INCLUDE" => "Y",
                    "PRODUCT_ID_VARIABLE" => "id",
                    "PRODUCT_PROPERTIES" => array(
                    ),
                    "PRODUCT_PROPS_VARIABLE" => "prop",
                    "PRODUCT_QUANTITY_VARIABLE" => "quantity",
                    "PRODUCT_ROW_VARIANTS" => "[{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false}]",
                    "PRODUCT_SUBSCRIPTION" => "Y",
                    "PROPERTY_CODE" => array(
                        0 => "",
                        1 => "",
                    ),
                    "PROPERTY_CODE_MOBILE" => array(
                    ),
                    "RCM_PROD_ID" => $_REQUEST["PRODUCT_ID"],
                    "RCM_TYPE" => "personal",
                    "SECTION_CODE" => "",
                    "SECTION_ID" => "",
                    "SECTION_ID_VARIABLE" => "SECTION_ID",
                    "SECTION_URL" => "",
                    "SECTION_USER_FIELDS" => array(
                        0 => "",
                        1 => "",
                    ),
                    "SEF_MODE" => "N",
                    "SET_BROWSER_TITLE" => "Y",
                    "SET_LAST_MODIFIED" => "N",
                    "SET_META_DESCRIPTION" => "Y",
                    "SET_META_KEYWORDS" => "Y",
                    "SET_STATUS_404" => "N",
                    "SET_TITLE" => "Y",
                    "SHOW_404" => "N",
                    "SHOW_ALL_WO_SECTION" => "Y",
                    "SHOW_CLOSE_POPUP" => "Y",
                    "SHOW_FROM_SECTION" => "N",
                    "SHOW_MAX_QUANTITY" => "N",
                    "SHOW_OLD_PRICE" => "Y",
                    "SHOW_PRICE_COUNT" => "1",
                    "TEMPLATE_THEME" => "site",
                    "USE_ENHANCED_ECOMMERCE" => "N",
                    "USE_MAIN_ELEMENT_SECTION" => "N",
                    "USE_PRICE_COUNT" => "N",
                    "USE_PRODUCT_QUANTITY" => "N",
                    "BXR_SHOW_MAX_QUANTITY" => "N",
                    "BXREADY_LIST_XLG_CNT_LISTPAGE" => "1",
                    "BXREADY_LIST_LG_CNT_LISTPAGE" => "1",
                    "BXREADY_LIST_MD_CNT_LISTPAGE" => "1",
                    "BXREADY_LIST_SM_CNT_LISTPAGE" => "1",
                    "BXREADY_LIST_XS_CNT_LISTPAGE" => "1",
                    "BXREADY_ELEMENT_ADDCLASS_LISTPAGE" => "",
                    "BXREADY_USE_ELEMENTCLASS_LISTPAGE" => "Y",
                    "BXREADY_VERTICAL_ALIGN_LISTPAGE" => "Y",
                    "BXREADY_ELEMENT_EXT_PARAMS_LISTPAGE" => "arrExtParams",
                    "BXREADY_USER_TYPES_LISTPAGE" => "N",
                    "BXREADY_ELEMENT_DRAW_LISTPAGE" => "ecommerce.m2.v1",
                    "BXREADY_LIST_SLIDER_LISTPAGE" => "N",
                    "COMPOSITE_FRAME_MODE" => "Y",
                    "COMPOSITE_FRAME_TYPE" => "DYNAMIC_WITH_STUB_LOADING",
                    "ENLARGE_PRODUCT" => "STRICT",
                    "PRODUCT_BLOCKS_ORDER" => "price,props,sku,quantityLimit,quantity,buttons,compare",
                    "SHOW_SLIDER" => "Y",
                    "LABEL_PROP" => "",
                    "SHOW_DISCOUNT_PERCENT" => "N",
                    "BXR_SHOW_RATING_LISTPAGE" => "avg",
                    "BXR_SHOW_ACTION_TIMER_LISTPAGE" => "N",
                    "BXR_SKU_PROPS_SHOW_TYPE_LISTPAGE" => "square",
                    "BXR_TILE_SHOW_PROPERTIES_LISTPAGE" => "N",
                    "BXREADY_LIST_MARKER_TYPE_LISTPAGE" => "not",
                    "BXREADY_LIST_OWN_MARKER_USE_LISTPAGE" => "N",
                    "BXR_SHOW_ARTICLE_LISTPAGE" => "Y",
                    "BXR_SHOW_SLIDER_LISTPAGE" => "Y",
                    "BXR_USE_FAST_VIEW_LISTPAGE" => "N",
                    "BXR_IMG_MAX_WIDTH_LISTPAGE" => "250",
                    "BXR_IMG_MAX_HEIGHT_LISTPAGE" => "250"
                ),
                false
            );?>
            <a href="/catalog-skidok/" class="news-all-video">Все товары со скидкой</a>
        </div>
        <div class="best-blocks best-block-new">
            <?
            $APPLICATION->IncludeComponent(
                "bxready.market2:catalog.section",
                "new",
                array(
                    "ACTION_VARIABLE" => "action",
                    "ADD_PICT_PROP" => "-",
                    "ADD_PROPERTIES_TO_BASKET" => "Y",
                    "ADD_SECTIONS_CHAIN" => "Y",
                    "ADD_TO_BASKET_ACTION" => "ADD",
                    "AJAX_MODE" => "Y",
                    "AJAX_OPTION_ADDITIONAL" => "",
                    "AJAX_OPTION_HISTORY" => "N",
                    "AJAX_OPTION_JUMP" => "N",
                    "AJAX_OPTION_STYLE" => "Y",
                    "BACKGROUND_IMAGE" => "-",
                    "BASKET_URL" => "/personal/basket.php",
                    "BROWSER_TITLE" => "-",
                    "BXREADY_ELEMENT_ADDCLASS_BIG" => "",
                    "BXREADY_ELEMENT_ADDCLASS_SMALL" => "",
                    "BXREADY_ELEMENT_ADDCLASS_STANDART" => "",
                    "BXREADY_ELEMENT_DRAW_BIG" => "ecommerce.m2.big.v1",
                    "BXREADY_ELEMENT_DRAW_LISTPAGE" => "ecommerce.m2.v1",
                    "BXREADY_ELEMENT_DRAW_SMALL" => "ecommerce.m2.small.v1",
                    "BXREADY_ELEMENT_DRAW_STANDART" => "ecommerce.m2.v1",
                    "BXREADY_ELEMENT_EXT_PARAMS_BIG" => "arrExtParams",
                    "BXREADY_ELEMENT_EXT_PARAMS_SMALL" => "arrExtParams",
                    "BXREADY_ELEMENT_EXT_PARAMS_STANDART" => "arrExtParams",
                    "BXREADY_LIST_MARKER_TYPE_BIG" => "circle.horizontal",
                    "BXREADY_LIST_MARKER_TYPE_STANDART" => "circle.horizontal",
                    "BXREADY_LIST_OWN_MARKER_USE_STANDART" => "N",
                    "BXREADY_USER_TYPES_BIG" => "N",
                    "BXREADY_USER_TYPES_SMALL" => "N",
                    "BXREADY_USER_TYPES_STANDART" => "N",
                    "BXREADY_USE_ELEMENTCLASS_BIG" => "Y",
                    "BXREADY_USE_ELEMENTCLASS_SMALL" => "Y",
                    "BXREADY_USE_ELEMENTCLASS_STANDART" => "Y",
                    "BXREADY_VERTICAL_ALIGN_BIG" => "Y",
                    "BXREADY_VERTICAL_ALIGN_SMALL" => "Y",
                    "BXREADY_VERTICAL_ALIGN_STANDART" => "Y",
                    "BXR_IMG_MAX_HEIGHT_BIG" => "210",
                    "BXR_IMG_MAX_HEIGHT_SMALL" => "90",
                    "BXR_IMG_MAX_HEIGHT_STANDART" => "250",
                    "BXR_IMG_MAX_WIDTH_BIG" => "210",
                    "BXR_IMG_MAX_WIDTH_SMALL" => "90",
                    "BXR_IMG_MAX_WIDTH_STANDART" => "250",
                    "BXR_SHOW_ACTION_TIMER_BIG" => "N",
                    "BXR_SHOW_ACTION_TIMER_STANDART" => "N",
                    "BXR_SHOW_ARTICLE_BIG" => "Y",
                    "BXR_SHOW_ARTICLE_STANDART" => "Y",
                    "BXR_SHOW_PREVIEW_TEXT_BIG" => "Y",
                    "BXR_SHOW_RATING_STANDART" => "N",
                    "BXR_SHOW_SLIDER_BIG" => "Y",
                    "BXR_SHOW_SLIDER_STANDART" => "Y",
                    "BXR_SKU_PROPS_SHOW_TYPE_BIG" => "rounded",
                    "BXR_SKU_PROPS_SHOW_TYPE_STANDART" => "square",
                    "BXR_SLIDER_INTERVAL_BIG" => "3000",
                    "BXR_SLIDER_INTERVAL_STANDART" => "0",
                    "BXR_TILE_SHOW_PROPERTIES_STANDART" => "N",
                    "BXR_USE_FAST_VIEW_BIG" => "N",
                    "BXR_USE_FAST_VIEW_SMALL" => "Y",
                    "BXR_USE_FAST_VIEW_STANDART" => "N",
                    "CACHE_FILTER" => "N",
                    "CACHE_GROUPS" => "Y",
                    "CACHE_TIME" => "36000000",
                    "CACHE_TYPE" => "A",
                    "COMPATIBLE_MODE" => "Y",
                    "COMPONENT_TEMPLATE" => "new",
                    "CONVERT_CURRENCY" => "N",
                    "CUSTOM_FILTER" => "{\"CLASS_ID\":\"CondGroup\",\"DATA\":{\"All\":\"OR\",\"True\":\"True\"},\"CHILDREN\":{\"12\":{\"CLASS_ID\":\"CondIBProp:44:413\",\"DATA\":{\"logic\":\"Equal\",\"value\":363}}}}",
                    "DETAIL_URL" => "",
                    "DISABLE_INIT_JS_IN_COMPONENT" => "N",
                    "DISPLAY_BOTTOM_PAGER" => "Y",
                    "DISPLAY_COMPARE" => "N",
                    "DISPLAY_TOP_PAGER" => "N",
                    "ELEMENT_SORT_FIELD" => $arSortGlobal["sort"],
                    "ELEMENT_SORT_FIELD2" => "rand",
                    "ELEMENT_SORT_ORDER" => $arSortGlobal["sort_order"],
                    "ELEMENT_SORT_ORDER2" => "desc",
                    "FILTER_NAME" => "arrFilter",
                    "HIDE_NOT_AVAILABLE" => "Y",
                    "HIDE_NOT_AVAILABLE_OFFERS" => "Y",
                    "IBLOCK_ID" => "44",
                    "IBLOCK_TYPE" => "catalog",
                    "INCLUDE_SUBSECTIONS" => "Y",
                    "LINE_ELEMENT_COUNT" => "4",
                    "MESSAGE_404" => "",
                    "MESS_BTN_ADD_TO_BASKET" => "В корзину",
                    "MESS_BTN_BUY" => "Купить",
                    "MESS_BTN_DETAIL" => "Подробнее",
                    "MESS_NOT_AVAILABLE" => "Нет в наличии",
                    "META_DESCRIPTION" => "-",
                    "META_KEYWORDS" => "-",
                    "OFFERS_LIMIT" => "5",
                    "PAGER_BASE_LINK_ENABLE" => "N",
                    "PAGE_BLOCK_TITLE" => "",
                    "PAGER_DESC_NUMBERING" => "N",
                    "PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
                    "PAGER_SHOW_ALL" => "N",
                    "PAGER_SHOW_ALWAYS" => "N",
                    "PAGER_TEMPLATE" => "new",
                    "PAGER_TITLE" => "Товары",
                    "PAGE_ELEMENT_COUNT" => "8",
                    "PARTIAL_PRODUCT_PROPERTIES" => "Y",
                    "PRICE_CODE" => array(
                        0 => "Розница",
                    ),
                    "PRICE_VAT_INCLUDE" => "Y",
                    "PRODUCT_ID_VARIABLE" => "id",
                    "PRODUCT_PROPERTIES" => array(
                    ),
                    "PRODUCT_PROPS_VARIABLE" => "prop",
                    "PRODUCT_QUANTITY_VARIABLE" => "quantity",
                    "PRODUCT_ROW_VARIANTS" => "[{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false}]",
                    "PRODUCT_SUBSCRIPTION" => "Y",
                    "PROPERTY_CODE" => array(
                        0 => "",
                        1 => "",
                    ),
                    "PROPERTY_CODE_MOBILE" => array(
                    ),
                    "RCM_PROD_ID" => $_REQUEST["PRODUCT_ID"],
                    "RCM_TYPE" => "personal",
                    "SECTION_CODE" => "",
                    "SECTION_ID" => "",
                    "SECTION_ID_VARIABLE" => "SECTION_ID",
                    "SECTION_URL" => "",
                    "SECTION_USER_FIELDS" => array(
                        0 => "",
                        1 => "",
                    ),
                    "SEF_MODE" => "N",
                    "SET_BROWSER_TITLE" => "Y",
                    "SET_LAST_MODIFIED" => "N",
                    "SET_META_DESCRIPTION" => "Y",
                    "SET_META_KEYWORDS" => "Y",
                    "SET_STATUS_404" => "N",
                    "SET_TITLE" => "Y",
                    "SHOW_404" => "N",
                    "SHOW_ALL_WO_SECTION" => "Y",
                    "SHOW_CLOSE_POPUP" => "Y",
                    "SHOW_FROM_SECTION" => "N",
                    "SHOW_MAX_QUANTITY" => "N",
                    "SHOW_OLD_PRICE" => "Y",
                    "SHOW_PRICE_COUNT" => "1",
                    "TEMPLATE_THEME" => "site",
                    "USE_ENHANCED_ECOMMERCE" => "N",
                    "USE_MAIN_ELEMENT_SECTION" => "N",
                    "USE_PRICE_COUNT" => "N",
                    "USE_PRODUCT_QUANTITY" => "N",
                    "BXR_SHOW_MAX_QUANTITY" => "N",
                    "BXREADY_LIST_XLG_CNT_LISTPAGE" => "1",
                    "BXREADY_LIST_LG_CNT_LISTPAGE" => "1",
                    "BXREADY_LIST_MD_CNT_LISTPAGE" => "1",
                    "BXREADY_LIST_SM_CNT_LISTPAGE" => "1",
                    "BXREADY_LIST_XS_CNT_LISTPAGE" => "1",
                    "BXREADY_ELEMENT_ADDCLASS_LISTPAGE" => "",
                    "BXREADY_USE_ELEMENTCLASS_LISTPAGE" => "Y",
                    "BXREADY_VERTICAL_ALIGN_LISTPAGE" => "Y",
                    "BXREADY_ELEMENT_EXT_PARAMS_LISTPAGE" => "arrExtParams",
                    "BXREADY_USER_TYPES_LISTPAGE" => "N",
                    "BXREADY_ELEMENT_DRAW_LISTPAGE" => "ecommerce.m2.v1",
                    "BXREADY_LIST_SLIDER_LISTPAGE" => "N",
                    "COMPOSITE_FRAME_MODE" => "Y",
                    "COMPOSITE_FRAME_TYPE" => "DYNAMIC_WITH_STUB_LOADING",
                    "ENLARGE_PRODUCT" => "STRICT",
                    "PRODUCT_BLOCKS_ORDER" => "price,props,sku,quantityLimit,quantity,buttons,compare",
                    "SHOW_SLIDER" => "Y",
                    "LABEL_PROP" => "",
                    "SHOW_DISCOUNT_PERCENT" => "N",
                    "BXR_SHOW_RATING_LISTPAGE" => "avg",
                    "BXR_SHOW_ACTION_TIMER_LISTPAGE" => "N",
                    "BXR_SKU_PROPS_SHOW_TYPE_LISTPAGE" => "square",
                    "BXR_TILE_SHOW_PROPERTIES_LISTPAGE" => "N",
                    "BXREADY_LIST_MARKER_TYPE_LISTPAGE" => "not",
                    "BXREADY_LIST_OWN_MARKER_USE_LISTPAGE" => "N",
                    "BXR_SHOW_ARTICLE_LISTPAGE" => "Y",
                    "BXR_SHOW_SLIDER_LISTPAGE" => "Y",
                    "BXR_USE_FAST_VIEW_LISTPAGE" => "N",
                    "BXR_IMG_MAX_WIDTH_LISTPAGE" => "250",
                    "BXR_IMG_MAX_HEIGHT_LISTPAGE" => "250",
                    "MESS_BTN_SUBSCRIBE" => "Подписаться",
                    "LAZY_LOAD" => "N",
                    "LOAD_ON_SCROLL" => "N",
                    "MESS_BTN_FAST_VIEW_SMALL" => "Быстрый просмотр"
                ),
                false
            );?>
        </div>
        <div class="best-blocks best-block-lider">
            <?$APPLICATION->IncludeComponent(
                "bitrix:sale.bestsellers",
                "custom",
                Array(
                    "ACTION_VARIABLE" => "action_slb",
                    "ADDITIONAL_PICT_PROP_0" => "-",
                    "ADDITIONAL_PICT_PROP_18" => "PICTURES_SKU",
                    "ADDITIONAL_PICT_PROP_41" => "dopimage",
                    "ADDITIONAL_PICT_PROP_44" => "dops",
                    "ADDITIONAL_PICT_PROP_49" => "dops",
                    "ADD_PROPERTIES_TO_BASKET" => "Y",
                    "ADD_TO_BASKET_ACTION" => "",
                    "AJAX_MODE" => "N",
                    "AJAX_OPTION_ADDITIONAL" => "",
                    "AJAX_OPTION_HISTORY" => "N",
                    "AJAX_OPTION_JUMP" => "N",
                    "AJAX_OPTION_STYLE" => "Y",
                    "BASKET_URL" => "/personal/basket.php",
                    "BXR_SALELEADER" => Array("BXREADY_ELEMENT_ADDCLASS"=>"","BXREADY_USE_ELEMENTCLASS"=>"Y","BXREADY_VERTICAL_ALIGN"=>"N","BXREADY_ELEMENT_EXT_PARAMS"=>"arrExtParams","BXREADY_USER_TYPES"=>"N","BXREADY_ELEMENT_DRAW"=>"ecommerce.m2.v1","BXR_SHOW_RATING"=>"N","BXR_SHOW_ACTION_TIMER"=>"N","BXR_TILE_SHOW_PROPERTIES"=>"Y","BXREADY_LIST_MARKER_TYPE"=>"circle.horizontal","BXREADY_LIST_OWN_MARKER_USE"=>"N","BXR_SHOW_ARTICLE"=>"Y","BXR_SHOW_SLIDER"=>"Y","BXR_SLIDER_INTERVAL"=>3000,"BXR_USE_FAST_VIEW"=>"N","MESS_BTN_FAST_VIEW"=>"Быстрый просмотр","BXREADY_LIST_XLG_CNT"=>4,"BXREADY_LIST_LG_CNT"=>4,"BXREADY_LIST_MD_CNT"=>4,"BXREADY_LIST_SM_CNT"=>2,"BXREADY_LIST_XS_CNT"=>1,"BXR_PRODUCT_BLOCKS_ORDER"=>"picture,name,rating,avail,article,price,buttons,action_timer,props","BXR_IMG_MAX_WIDTH"=>250,"BXR_IMG_MAX_HEIGHT"=>250,"SHOW_MAX_QUANTITY"=>"Y","BXR_SKU_PROPS_SHOW_TYPE"=>"rounded","BXREADY_USER_TYPE_VARIANT"=>"","BXR_SHOW_PREVIEW_TEXT"=>"Y",),
                    "BXR_SHOW_MAX_QUANTITY" => "A",
                    "BY" => "AMOUNT",
                    "CACHE_FILTER" => "Y",
                    "CACHE_GROUPS" => "Y",
                    "CACHE_TIME" => "36000000",
                    "CACHE_TYPE" => "A",
                    "CART_PROPERTIES_18" => array("",""),
                    "CART_PROPERTIES_41" => array(""),
                    "CART_PROPERTIES_44" => array("",""),
                    "CART_PROPERTIES_49" => array(""),
                    "COMPARE_NAME" => "CATALOG_COMPARE_LIST",
                    "COMPARE_PATH" => "/catalog/#SECTION_CODE_PATH#/compare.php?action=#ACTION_CODE#",
                    "COMPONENT_TEMPLAT" => "",
                    "COMPOSITE_FRAME_MODE" => "A",
                    "COMPOSITE_FRAME_TYPE" => "AUTO",
                    "CONVERT_CURRENCY" => "Y",
                    "CURRENCY_ID" => "RUB",
                    "DETAIL_URL" => "/catalog/#SECTION_CODE_PATH#/#ELEMENT_CODE#/",
                    "DISPLAY_COMPARE" => "N",
                    "ELEMENT_SORT_FIELD" => "",
                    "ELEMENT_SORT_FIELD2" => "sort",
                    "ELEMENT_SORT_ORDER" => "",
                    "ELEMENT_SORT_ORDER2" => "asc",
                    "FILTER" => array("CANCELED","ALLOW_DELIVERY","PAYED","DEDUCTED","N","P","F"),
                    "FILTER_NAME" => "arrFilter",
                    "HIDE_NOT_AVAILABLE" => "Y",
                    "HIDE_NOT_AVAILABLE_OFFERS" => "Y",
                    "IBLOCK_ID" => 44,
                    "IBLOCK_TYPE" => "catalog",
                    "LABEL_PROP_41" => "-",
                    "LABEL_PROP_44" => "-",
                    "LABEL_PROP_49" => "-",
                    "LINE_ELEMENT_COUNT" => "10",
                    "MESS_BTN_ADD_TO_BASKET" => "В корзину",
                    "MESS_BTN_BUY" => "Купить",
                    "MESS_BTN_COMPARE" => "Сравнение",
                    "MESS_BTN_DETAIL" => "Подробнее",
                    "MESS_BTN_SUBSCRIBE" => "Сообщить о поступлении",
                    "MESS_NOT_AVAILABLE" => "Нет в наличии",
                    "MESS_RELATIVE_QUANTITY_FEW" => "мало",
                    "MESS_RELATIVE_QUANTITY_MANY" => "много",
                    "MESS_SHOW_MAX_QUANTITY" => "Наличие",
                    "OFFERS_CART_PROPERTIES" => "",
                    "OFFERS_FIELD_CODE" => Array("0"=>"","1"=>""),
                    "OFFERS_LIMIT" => 0,
                    "OFFERS_PROPERTY_CODE" => Array("0"=>"","1"=>""),
                    "OFFERS_SORT_FIELD" => "shows",
                    "OFFERS_SORT_FIELD2" => "shows",
                    "OFFERS_SORT_ORDER" => "asc",
                    "OFFERS_SORT_ORDER2" => "asc",
                    "OFFER_TREE_PROPS_0" => "",
                    "OFFER_TREE_PROPS_18" => array(),
                    "ORDER_FILTER_NAME" => "arOrderFilter",
                    "PAGE_BLOCK_TITLE" => "Лидеры продаж",
                    "PAGE_ELEMENT_COUNT" => "9",
                    "PARTIAL_PRODUCT_PROPERTIES" => "N",
                    "PERIOD" => "365",
                    "PRICE_CODE" => array("Розница"),
                    "PRICE_VAT_INCLUDE" => "Y",
                    "PRODUCT_DISPLAY_MODE" => "N",
                    "PRODUCT_ID_VARIABLE" => "id",
                    "PRODUCT_PROPERTIES" => Array(),
                    "PRODUCT_PROPS_VARIABLE" => "prop",
                    "PRODUCT_QUANTITY_VARIABLE" => "quantity",
                    "PRODUCT_SUBSCRIPTION" => "N",
                    "PROPERTY_CODE" => Array("0"=>"attraktant","1"=>"dlina","2"=>"test_po_primankam","3"=>"tip_primanki","4"=>"Длина, см","5"=>""),
                    "PROPERTY_CODE_18" => array("",""),
                    "PROPERTY_CODE_41" => array(""),
                    "PROPERTY_CODE_44" => array("",""),
                    "PROPERTY_CODE_49" => array(""),
                    "PROPERTY_CODE_MOBILE" => Array("0"=>"dlina",),
                    "QUANTITY_IN_STOCK" => "В наличии",
                    "QUANTITY_OUT_STOCK" => "В наличии",
                    "RELATIVE_QUANTITY_FACTOR" => 10,
                    "SHOW_CLOSE_POPUP" => "Y",
                    "SHOW_DISCOUNT_PERCENT" => "Y",
                    "SHOW_IMAGE" => "Y",
                    "SHOW_NAME" => "Y",
                    "SHOW_OLD_PRICE" => "Y",
                    "SHOW_PRICE_COUNT" => "1",
                    "SHOW_PRODUCTS_41" => "N",
                    "SHOW_PRODUCTS_44" => "Y",
                    "SHOW_PRODUCTS_49" => "N",
                    "TEMPLATE_THEME" => "",
                    "THIS_UNIC_ID" => "bestsellers",
                    "USE_PRICE_COUNT" => "N",
                    "USE_PRODUCT_QUANTITY" => "N"
                ),
                $component,
                Array(
                    'HIDE_ICONS' => 'Y'
                )
            );?>
        </div>
        <?/*<div class="best-blocks best-block-contactless">
            <?  $APPLICATION->IncludeComponent(
                "bxready.market2:catalog.section",
                "custom",
                array(
                    "ACTION_VARIABLE" => "action",
                    "ADD_PICT_PROP" => "-",
                    "ADD_PROPERTIES_TO_BASKET" => "Y",
                    "ADD_SECTIONS_CHAIN" => "Y",
                    "ADD_TO_BASKET_ACTION" => "ADD",
                    "AJAX_MODE" => "N",
                    "AJAX_OPTION_ADDITIONAL" => "",
                    "AJAX_OPTION_HISTORY" => "N",
                    "AJAX_OPTION_JUMP" => "N",
                    "AJAX_OPTION_STYLE" => "Y",
                    "BACKGROUND_IMAGE" => "-",
                    "BASKET_URL" => "/personal/basket.php",
                    "BROWSER_TITLE" => "-",
                    "BXREADY_ELEMENT_ADDCLASS_BIG" => "",
                    "BXREADY_ELEMENT_ADDCLASS_LISTPAGE" => "",
                    "BXREADY_ELEMENT_ADDCLASS_SMALL" => "",
                    "BXREADY_ELEMENT_ADDCLASS_STANDART" => "",
                    "BXREADY_ELEMENT_DRAW_BIG" => "ecommerce.m2.big.v1",
                    "BXREADY_ELEMENT_DRAW_LISTPAGE" => "ecommerce.m2.v1",
                    "BXREADY_ELEMENT_DRAW_SMALL" => "ecommerce.m2.small.v1",
                    "BXREADY_ELEMENT_DRAW_STANDART" => "ecommerce.m2.v1",
                    "BXREADY_ELEMENT_EXT_PARAMS_BIG" => "arrExtParams",
                    "BXREADY_ELEMENT_EXT_PARAMS_LISTPAGE" => "arrExtParams",
                    "BXREADY_ELEMENT_EXT_PARAMS_SMALL" => "arrExtParams",
                    "BXREADY_ELEMENT_EXT_PARAMS_STANDART" => "arrExtParams",
                    "BXREADY_LIST_LG_CNT_LISTPAGE" => "1",
                    "BXREADY_LIST_MARKER_TYPE_BIG" => "circle.horizontal",
                    "BXREADY_LIST_MARKER_TYPE_STANDART" => "circle.horizontal",
                    "BXREADY_LIST_MD_CNT_LISTPAGE" => "1",
                    "BXREADY_LIST_OWN_MARKER_USE_STANDART" => "N",
                    "BXREADY_LIST_SLIDER_LISTPAGE" => "N",
                    "BXREADY_LIST_SM_CNT_LISTPAGE" => "1",
                    "BXREADY_LIST_XLG_CNT_LISTPAGE" => "1",
                    "BXREADY_LIST_XS_CNT_LISTPAGE" => "1",
                    "BXREADY_USER_TYPES_BIG" => "N",
                    "BXREADY_USER_TYPES_LISTPAGE" => "N",
                    "BXREADY_USER_TYPES_SMALL" => "N",
                    "BXREADY_USER_TYPES_STANDART" => "N",
                    "BXREADY_USE_ELEMENTCLASS_BIG" => "Y",
                    "BXREADY_USE_ELEMENTCLASS_LISTPAGE" => "Y",
                    "BXREADY_USE_ELEMENTCLASS_SMALL" => "Y",
                    "BXREADY_USE_ELEMENTCLASS_STANDART" => "Y",
                    "BXREADY_VERTICAL_ALIGN_BIG" => "Y",
                    "BXREADY_VERTICAL_ALIGN_LISTPAGE" => "Y",
                    "BXREADY_VERTICAL_ALIGN_SMALL" => "Y",
                    "BXREADY_VERTICAL_ALIGN_STANDART" => "Y",
                    "BXR_IMG_MAX_HEIGHT_BIG" => "210",
                    "BXR_IMG_MAX_HEIGHT_SMALL" => "90",
                    "BXR_IMG_MAX_HEIGHT_STANDART" => "250",
                    "BXR_IMG_MAX_WIDTH_BIG" => "210",
                    "BXR_IMG_MAX_WIDTH_SMALL" => "90",
                    "BXR_IMG_MAX_WIDTH_STANDART" => "250",
                    "BXR_SHOW_ACTION_TIMER_BIG" => "N",
                    "BXR_SHOW_ACTION_TIMER_STANDART" => "N",
                    "BXR_SHOW_ARTICLE_BIG" => "Y",
                    "BXR_SHOW_ARTICLE_STANDART" => "Y",
                    "BXR_SHOW_MAX_QUANTITY" => "N",
                    "BXR_SHOW_PREVIEW_TEXT_BIG" => "Y",
                    "BXR_SHOW_RATING_STANDART" => "N",
                    "BXR_SHOW_SLIDER_BIG" => "Y",
                    "BXR_SHOW_SLIDER_STANDART" => "Y",
                    "BXR_SKU_PROPS_SHOW_TYPE_BIG" => "rounded",
                    "BXR_SKU_PROPS_SHOW_TYPE_STANDART" => "square",
                    "BXR_SLIDER_INTERVAL_BIG" => "3000",
                    "BXR_SLIDER_INTERVAL_STANDART" => "0",
                    "BXR_TILE_SHOW_PROPERTIES_STANDART" => "N",
                    "BXR_USE_FAST_VIEW_BIG" => "N",
                    "BXR_USE_FAST_VIEW_SMALL" => "Y",
                    "BXR_USE_FAST_VIEW_STANDART" => "N",
                    "CACHE_FILTER" => "N",
                    "CACHE_GROUPS" => "Y",
                    "CACHE_TIME" => "36000000",
                    "CACHE_TYPE" => "A",
                    "COMPATIBLE_MODE" => "Y",
                    "COMPONENT_TEMPLATE" => "custom",
                    "COMPOSITE_FRAME_MODE" => "A",
                    "COMPOSITE_FRAME_TYPE" => "AUTO",
                    "CONVERT_CURRENCY" => "N",
                    "CUSTOM_FILTER" => "{\"CLASS_ID\":\"CondGroup\",\"DATA\":{\"All\":\"AND\",\"True\":\"True\"},\"CHILDREN\":{\"1\":{\"CLASS_ID\":\"CondIBProp:44:434\",\"DATA\":{\"logic\":\"Equal\",\"value\":414}}}}",
                    "DETAIL_URL" => "",
                    "DISABLE_INIT_JS_IN_COMPONENT" => "N",
                    "DISPLAY_BOTTOM_PAGER" => "N",
                    "DISPLAY_COMPARE" => "N",
                    "DISPLAY_TOP_PAGER" => "N",
                    "ELEMENT_SORT_FIELD" => $arSortGlobal["sort"],
                    "ELEMENT_SORT_FIELD2" => "id",
                    "ELEMENT_SORT_ORDER" => $arSortGlobal["sort_order"],
                    "ELEMENT_SORT_ORDER2" => "desc",
                    "FILTER_NAME" => "arrFilter",
                    "HIDE_NOT_AVAILABLE" => "Y",
                    "HIDE_NOT_AVAILABLE_OFFERS" => "Y",
                    "IBLOCK_ID" => "44",
                    "IBLOCK_TYPE" => "catalog",
                    "INCLUDE_SUBSECTIONS" => "Y",
                    "LAZY_LOAD" => "Y",
                    "LINE_ELEMENT_COUNT" => "4",
                    "LOAD_ON_SCROLL" => "N",
                    "MESSAGE_404" => "",
                    "MESS_BTN_ADD_TO_BASKET" => "В корзину",
                    "MESS_BTN_BUY" => "Купить",
                    "MESS_BTN_DETAIL" => "Подробнее",
                    "MESS_BTN_FAST_VIEW_SMALL" => "Быстрый просмотр",
                    "MESS_BTN_LAZY_LOAD" => "Показать ещё",
                    "MESS_BTN_SUBSCRIBE" => "Подписаться",
                    "MESS_NOT_AVAILABLE" => "Нет в наличии",
                    "META_DESCRIPTION" => "-",
                    "META_KEYWORDS" => "-",
                    "OFFERS_LIMIT" => "5",
                    "PAGER_BASE_LINK_ENABLE" => "N",
                    "PAGER_DESC_NUMBERING" => "N",
                    "PAGER_DESC_NUMBERING_CACHE_TIME" => "36000",
                    "PAGER_SHOW_ALL" => "N",
                    "PAGER_SHOW_ALWAYS" => "N",
                    "PAGER_TEMPLATE" => "custom_new",
                    "PAGER_TITLE" => "Товары",
                    "PAGE_BLOCK_TITLE" => "",
                    "PAGE_ELEMENT_COUNT" => "8",
                    "PARTIAL_PRODUCT_PROPERTIES" => "Y",
                    "PRICE_CODE" => array(
                        0 => "Розница",
                    ),
                    "PRICE_VAT_INCLUDE" => "Y",
                    "PRODUCT_ID_VARIABLE" => "id",
                    "PRODUCT_PROPERTIES" => array(
                    ),
                    "PRODUCT_PROPS_VARIABLE" => "prop",
                    "PRODUCT_QUANTITY_VARIABLE" => "quantity",
                    "PRODUCT_ROW_VARIANTS" => "[{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false},{'VARIANT':'2','BIG_DATA':false}]",
                    "PRODUCT_SUBSCRIPTION" => "Y",
                    "PROPERTY_CODE" => array(
                        0 => "",
                        1 => "",
                    ),
                    "PROPERTY_CODE_MOBILE" => array(
                    ),
                    "RCM_PROD_ID" => $_REQUEST["PRODUCT_ID"],
                    "RCM_TYPE" => "personal",
                    "SECTION_CODE" => "",
                    "SECTION_ID" => "",
                    "SECTION_ID_VARIABLE" => "SECTION_ID",
                    "SECTION_URL" => "",
                    "SECTION_USER_FIELDS" => array(
                        0 => "",
                        1 => "",
                    ),
                    "SEF_MODE" => "N",
                    "SET_BROWSER_TITLE" => "Y",
                    "SET_LAST_MODIFIED" => "N",
                    "SET_META_DESCRIPTION" => "Y",
                    "SET_META_KEYWORDS" => "Y",
                    "SET_STATUS_404" => "N",
                    "SET_TITLE" => "Y",
                    "SHOW_404" => "N",
                    "SHOW_ALL_WO_SECTION" => "Y",
                    "SHOW_CLOSE_POPUP" => "Y",
                    "SHOW_FROM_SECTION" => "N",
                    "SHOW_MAX_QUANTITY" => "N",
                    "SHOW_OLD_PRICE" => "Y",
                    "SHOW_PRICE_COUNT" => "1",
                    "TEMPLATE_THEME" => "site",
                    "USE_ENHANCED_ECOMMERCE" => "N",
                    "USE_MAIN_ELEMENT_SECTION" => "N",
                    "USE_PRICE_COUNT" => "N",
                    "USE_PRODUCT_QUANTITY" => "N"
                ),
                false
            );?>
            <a href="/catalog/contactless/" class="news-all-video news-all-contactless">Все товары с бесконтактной доставкой</a>
        </div>*/?>
    </div>
</div>
<script>
    $(document).ready(function(){
        $(".bxr-bestsellers-group").click(function () {
            $link = $(this).attr('value');
            $(".bxr-bestsellers-group").removeClass('best-active');
            $(".best-blocks").hide();
            $(this).addClass('best-active');
            $(".best-block-"+$link).show();
        });
        $(".bxr-bestsellers-first").trigger('click');
    })
</script>