<?
require($_SERVER["DOCUMENT_ROOT"]."/bitrix/header.php");
$APPLICATION->SetTitle("Заказы");
?>

<?if ($arMinOrderPrice["ADD_PRICE"] <= 0 || $_REQUEST["ORDER_ID"]) {?>
    <?$APPLICATION->IncludeComponent(
        "bitrix:sale.order.ajax",
        "bonusD7_custom",
        array(
            "PAY_FROM_ACCOUNT" => "Y",
            "COUNT_DELIVERY_TAX" => "N",
            "COUNT_DISCOUNT_4_ALL_QUANTITY" => "N",
            "ONLY_FULL_PAY_FROM_ACCOUNT" => "Y",
            "ALLOW_AUTO_REGISTER" => "Y",
            "SEND_NEW_USER_NOTIFY" => "Y",
            "DELIVERY_NO_AJAX" => "N",
            "TEMPLATE_LOCATION" => "popup",
            "PROP_1" => "",
            "PATH_TO_BASKET" => SITE_DIR."personal/basket/",
            "PATH_TO_PERSONAL" => SITE_DIR."personal/orders/",
            "PATH_TO_PAYMENT" => SITE_DIR."personal/order/payment/",
            "PATH_TO_ORDER" => SITE_DIR."personal/order/make/",
            "SET_TITLE" => "Y",
            "DELIVERY2PAY_SYSTEM" => "",
            "SHOW_ACCOUNT_NUMBER" => "Y",
            "DELIVERY_NO_SESSION" => "Y",
            "COMPONENT_TEMPLATE" => "bonusD7_custom",
            "DELIVERY_TO_PAYSYSTEM" => "d2p",
            "USE_PREPAYMENT" => "N",
            "ALLOW_NEW_PROFILE" => "N",
            "SHOW_PAYMENT_SERVICES_NAMES" => "Y",
            "SHOW_STORES_IMAGES" => "N",
            "PATH_TO_AUTH" => SITE_DIR."auth/",
            "DISABLE_BASKET_REDIRECT" => "N",
            "PRODUCT_COLUMNS" => "",
            "ALLOW_APPEND_ORDER" => "Y",
            "SHOW_NOT_CALCULATED_DELIVERIES" => "L",
            "SPOT_LOCATION_BY_GEOIP" => "N",
            "SHOW_VAT_PRICE" => "Y",
            "COMPATIBLE_MODE" => "Y",
            "USE_PRELOAD" => "Y",
            "ALLOW_USER_PROFILES" => "N",
            "TEMPLATE_THEME" => "site",
            "SHOW_ORDER_BUTTON" => "final_step",
            "SHOW_TOTAL_ORDER_BUTTON" => "N",
            "SHOW_PAY_SYSTEM_LIST_NAMES" => "Y",
            "SHOW_PAY_SYSTEM_INFO_NAME" => "Y",
            "SHOW_DELIVERY_LIST_NAMES" => "Y",
            "SHOW_DELIVERY_INFO_NAME" => "Y",
            "SHOW_DELIVERY_PARENT_NAMES" => "Y",
            "SKIP_USELESS_BLOCK" => "Y",
            "BASKET_POSITION" => "after",
            "SHOW_BASKET_HEADERS" => "N",
            "DELIVERY_FADE_EXTRA_SERVICES" => "N",
            "SHOW_COUPONS_BASKET" => "Y",
            "SHOW_COUPONS_DELIVERY" => "Y",
            "SHOW_COUPONS_PAY_SYSTEM" => "Y",
            "SHOW_NEAREST_PICKUP" => "N",
            "DELIVERIES_PER_PAGE" => "9",
            "PAY_SYSTEMS_PER_PAGE" => "9",
            "PICKUPS_PER_PAGE" => "5",
            "SHOW_PICKUP_MAP" => "Y",
            "SHOW_MAP_IN_PROPS" => "N",
            "PICKUP_MAP_TYPE" => "yandex",
            "PROPS_FADE_LIST_1" => array(
                0 => "1",
                1 => "2",
                2 => "3",
                3 => "7",
            ),
            "PROPS_FADE_LIST_2" => array(
                0 => "8",
                1 => "12",
                2 => "13",
                3 => "14",
                4 => "19",
            ),
            "USER_CONSENT" => "N",
            "ACTION_VARIABLE" => "action",
            "PRODUCT_COLUMNS_VISIBLE" => array(
                0 => "PREVIEW_PICTURE",
                1 => "PROPS",
            ),
            "ADDITIONAL_PICT_PROP_12" => "-",
            "ADDITIONAL_PICT_PROP_13" => "-",
            "BASKET_IMAGES_SCALING" => "adaptive",
            "SERVICES_IMAGES_SCALING" => "adaptive",
            "PRODUCT_COLUMNS_HIDDEN" => array(
            ),
            "USE_YM_GOALS" => "N",
            "USE_ENHANCED_ECOMMERCE" => "N",
            "USE_CUSTOM_MAIN_MESSAGES" => "N",
            "USE_CUSTOM_ADDITIONAL_MESSAGES" => "N",
            "USE_CUSTOM_ERROR_MESSAGES" => "N",
            "PROPS_FADE_LIST_4" => array(
            ),
            "USER_CONSENT_ID" => "0",
            "USER_CONSENT_IS_CHECKED" => "Y",
            "USER_CONSENT_IS_LOADED" => "N",
            "USE_PHONE_NORMALIZATION" => "Y",
            "ADDITIONAL_PICT_PROP_18" => "-",
            "ADDITIONAL_PICT_PROP_36" => "-",
            "ADDITIONAL_PICT_PROP_37" => "-",
            "ADDITIONAL_PICT_PROP_41" => "-",
            "ADDITIONAL_PICT_PROP_44" => "-",
            "SHOW_BONUS_SYSTEM" => "Y",
            "ITR_BONUS_PATH_TO_HELP" => "",
            "ITR_BONUS_TEXT_TO_HELP" => "Бонус",
            "EMPTY_BASKET_HINT_PATH" => "/",
            "ADDITIONAL_PICT_PROP_49" => "-",
            "HIDE_ORDER_DESCRIPTION" => "N",
            "COMPOSITE_FRAME_MODE" => "A",
            "COMPOSITE_FRAME_TYPE" => "AUTO",
            "SHOW_COUPONS" => "Y"
        ),
        false
    );?>
<?}?>
<?require($_SERVER["DOCUMENT_ROOT"]."/bitrix/footer.php");?>